# Generated by Django 2.2.4 on 2019-08-10 12:35

import alerts.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('video', models.FileField(upload_to=alerts.models.content_file_name)),
                ('name', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Alert Events',
            },
        ),
    ]
